name: pss
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.12.31=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.20=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - ace-tools==0.0
      - antspyx==0.5.4
      - asttokens==3.0.0
      - astunparse==1.6.3
      - backcall==0.2.0
      - cachetools==5.5.1
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.8
      - comm==0.2.2
      - contextlib2==21.6.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.11
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - dominate==2.7.0
      - einops==0.8.0
      - executing==2.1.0
      - filelock==3.16.1
      - flatbuffers==25.1.24
      - fonttools==4.55.3
      - fsspec==2024.12.0
      - gast==0.4.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.70.0
      - h5py==3.11.0
      - idna==3.10
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.5
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - keras==2.13.1
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.8
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightning-utilities==0.11.9
      - lmdb==1.6.2
      - lpips==0.1.4
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - ml-collections==0.1.1
      - monai-weekly==1.4.dev2427
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.1
      - nibabel==5.2.1
      - numpy==1.23.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.4.2
      - oauthlib==3.2.2
      - opencv-python==4.5.5.64
      - opt-einsum==3.4.0
      - packaging==24.2
      - pandas==1.5.3
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.4.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.48
      - protobuf==3.20.3
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydicom==2.3.1
      - pygments==2.19.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-fid==0.3.0
      - pytz==2024.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-image==0.21.0
      - scipy==1.10.1
      - segment-anything==1.0
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - statsmodels==0.14.1
      - sympy==1.13.3
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - tifffile==2023.7.10
      - timm==0.4.12
      - torch==2.1.2
      - torch-fidelity==0.3.0
      - torchmetrics==1.4.0.post0
      - torchshow==0.5.1
      - torchvision==0.16.2
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==2.1.0
      - typing-extensions==4.5.0
      - urllib3==1.26.20
      - visdom==0.2.4
      - wandb==0.18.7
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - websocket-client==1.8.0
      - werkzeug==3.0.6
      - wrapt==1.17.2
      - zipp==3.20.2
prefix: /home/peiyuan/ENTER/envs/pss
